# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrentzone', '0002_torrentmodel_torrentinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrentmodel',
            name='torrentLink',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
